/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Manfred Armijos
 */
public class ViewPort extends javax.swing.JFrame {

    /**
     * Creates new form Plantilla
     */
    public ViewPort() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblFormName = new javax.swing.JLabel();
        lblFormIMO = new javax.swing.JLabel();
        lblFormLength = new javax.swing.JLabel();
        lblFormType = new javax.swing.JLabel();
        lblFormCapacity = new javax.swing.JLabel();
        lblFormQuantity = new javax.swing.JLabel();
        txfName = new javax.swing.JTextField();
        txfImo = new javax.swing.JTextField();
        txfLength = new javax.swing.JTextField();
        txfCapacity = new javax.swing.JTextField();
        txfQuantity = new javax.swing.JTextField();
        btnForm = new javax.swing.JButton();
        cbxType = new javax.swing.JComboBox<>();
        lblErrorFormQuantity = new javax.swing.JLabel();
        lblErrorFormName = new javax.swing.JLabel();
        lblErrorFormIMO = new javax.swing.JLabel();
        lblErrorFormLength = new javax.swing.JLabel();
        lblErrorFormType = new javax.swing.JLabel();
        lblErrorFormCapacity = new javax.swing.JLabel();
        lblFormIMO1 = new javax.swing.JLabel();
        lblFormLength1 = new javax.swing.JLabel();
        txfImo1 = new javax.swing.JTextField();
        txfLength1 = new javax.swing.JTextField();
        lblErrorFormIMO1 = new javax.swing.JLabel();
        lblErrorFormLength1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(15, 20, 25));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(30, 40, 53));
        jPanel2.setPreferredSize(new java.awt.Dimension(610, 610));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormName.setBackground(new java.awt.Color(255, 255, 255));
        lblFormName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFormName.setForeground(new java.awt.Color(189, 195, 199));
        lblFormName.setText("Name");
        jPanel2.add(lblFormName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        lblFormIMO.setBackground(new java.awt.Color(255, 255, 255));
        lblFormIMO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFormIMO.setForeground(new java.awt.Color(189, 195, 199));
        lblFormIMO.setText("IMO");
        jPanel2.add(lblFormIMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        lblFormLength.setBackground(new java.awt.Color(255, 255, 255));
        lblFormLength.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFormLength.setForeground(new java.awt.Color(189, 195, 199));
        lblFormLength.setText("Length");
        jPanel2.add(lblFormLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        lblFormType.setBackground(new java.awt.Color(255, 255, 255));
        lblFormType.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFormType.setForeground(new java.awt.Color(189, 195, 199));
        lblFormType.setText("Type");
        jPanel2.add(lblFormType, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        lblFormCapacity.setBackground(new java.awt.Color(255, 255, 255));
        lblFormCapacity.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFormCapacity.setForeground(new java.awt.Color(189, 195, 199));
        lblFormCapacity.setText("CapacityTEU");
        jPanel2.add(lblFormCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        lblFormQuantity.setBackground(new java.awt.Color(255, 255, 255));
        lblFormQuantity.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFormQuantity.setForeground(new java.awt.Color(189, 195, 199));
        lblFormQuantity.setText("Container");
        jPanel2.add(lblFormQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        txfName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfName.setPreferredSize(new java.awt.Dimension(240, 40));
        jPanel2.add(txfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        txfImo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfImo.setPreferredSize(new java.awt.Dimension(240, 40));
        txfImo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfImoActionPerformed(evt);
            }
        });
        jPanel2.add(txfImo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        txfLength.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfLength.setPreferredSize(new java.awt.Dimension(240, 40));
        jPanel2.add(txfLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        txfCapacity.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfCapacity.setPreferredSize(new java.awt.Dimension(240, 40));
        jPanel2.add(txfCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        txfQuantity.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfQuantity.setPreferredSize(new java.awt.Dimension(240, 40));
        jPanel2.add(txfQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        btnForm.setBackground(new java.awt.Color(0, 193, 212));
        btnForm.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnForm.setText("Next");
        btnForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormActionPerformed(evt);
            }
        });
        jPanel2.add(btnForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 200, 50));

        cbxType.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "CRUISE", "CONTAINER" }));
        cbxType.setPreferredSize(new java.awt.Dimension(240, 40));
        jPanel2.add(cbxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        lblErrorFormQuantity.setForeground(new java.awt.Color(255, 158, 0));
        jPanel2.add(lblErrorFormQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 240, 20));

        lblErrorFormName.setForeground(new java.awt.Color(255, 158, 0));
        jPanel2.add(lblErrorFormName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 240, 20));

        lblErrorFormIMO.setForeground(new java.awt.Color(255, 158, 0));
        jPanel2.add(lblErrorFormIMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 240, 20));

        lblErrorFormLength.setForeground(new java.awt.Color(255, 158, 0));
        jPanel2.add(lblErrorFormLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 240, 20));

        lblErrorFormType.setForeground(new java.awt.Color(255, 158, 0));
        jPanel2.add(lblErrorFormType, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 240, 20));

        lblErrorFormCapacity.setForeground(new java.awt.Color(255, 158, 0));
        jPanel2.add(lblErrorFormCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 240, 20));

        lblFormIMO1.setBackground(new java.awt.Color(255, 255, 255));
        lblFormIMO1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFormIMO1.setForeground(new java.awt.Color(189, 195, 199));
        lblFormIMO1.setText("Bean");
        jPanel2.add(lblFormIMO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        lblFormLength1.setBackground(new java.awt.Color(255, 255, 255));
        lblFormLength1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFormLength1.setForeground(new java.awt.Color(189, 195, 199));
        lblFormLength1.setText("Draft");
        jPanel2.add(lblFormLength1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        txfImo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfImo1.setPreferredSize(new java.awt.Dimension(240, 40));
        jPanel2.add(txfImo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        txfLength1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfLength1.setPreferredSize(new java.awt.Dimension(240, 40));
        jPanel2.add(txfLength1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        lblErrorFormIMO1.setForeground(new java.awt.Color(255, 158, 0));
        jPanel2.add(lblErrorFormIMO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 240, 20));

        lblErrorFormLength1.setForeground(new java.awt.Color(255, 158, 0));
        jPanel2.add(lblErrorFormLength1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 240, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 640));

        jPanel3.setBackground(new java.awt.Color(30, 40, 53));
        jPanel3.setPreferredSize(new java.awt.Dimension(610, 610));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(30, 40, 53));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 590, 290));

        jButton1.setBackground(new java.awt.Color(10, 107, 207));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("D");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 100, 70));

        jButton3.setBackground(new java.awt.Color(10, 107, 207));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setText("C");
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 70));

        jButton4.setBackground(new java.awt.Color(10, 107, 207));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setText("R");
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 100, 70));

        jButton5.setBackground(new java.awt.Color(10, 107, 207));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton5.setText("U");
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 100, 70));

        jButton2.setBackground(new java.awt.Color(10, 107, 207));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 100, 80));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1296, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormActionPerformed
    }//GEN-LAST:event_btnFormActionPerformed

    private void txfImoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfImoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfImoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ViewMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForm;
    private javax.swing.JComboBox<String> cbxType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblErrorFormCapacity;
    private javax.swing.JLabel lblErrorFormIMO;
    private javax.swing.JLabel lblErrorFormIMO1;
    private javax.swing.JLabel lblErrorFormLength;
    private javax.swing.JLabel lblErrorFormLength1;
    private javax.swing.JLabel lblErrorFormName;
    private javax.swing.JLabel lblErrorFormQuantity;
    private javax.swing.JLabel lblErrorFormType;
    private javax.swing.JLabel lblFormCapacity;
    private javax.swing.JLabel lblFormIMO;
    private javax.swing.JLabel lblFormIMO1;
    private javax.swing.JLabel lblFormLength;
    private javax.swing.JLabel lblFormLength1;
    private javax.swing.JLabel lblFormName;
    private javax.swing.JLabel lblFormQuantity;
    private javax.swing.JLabel lblFormType;
    private javax.swing.JTextField txfCapacity;
    private javax.swing.JTextField txfImo;
    private javax.swing.JTextField txfImo1;
    private javax.swing.JTextField txfLength;
    private javax.swing.JTextField txfLength1;
    private javax.swing.JTextField txfName;
    private javax.swing.JTextField txfQuantity;
    // End of variables declaration//GEN-END:variables
}
