/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Manfred Armijos
 */
public class ViewLogin extends javax.swing.JFrame {

    /**
     * Creates new form Plantilla
     */
    public ViewLogin() {
        initComponents();
        setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pnlLogin = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblKey = new javax.swing.JLabel();
        txfUser = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        lblErrorKey = new javax.swing.JLabel();
        psfKey = new javax.swing.JPasswordField();
        lblIconKey = new javax.swing.JLabel();
        lblIconUser = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(15, 20, 25));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(30, 40, 53));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 180, 290));

        jButton1.setBackground(new java.awt.Color(10, 107, 207));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Salir");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 100, 70));

        pnlLogin.setBackground(new java.awt.Color(30, 40, 53));
        pnlLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 58, 88), 4, true));
        pnlLogin.setPreferredSize(new java.awt.Dimension(600, 700));
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(189, 195, 199));
        lblUser.setText("USER");
        pnlLogin.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        lblKey.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblKey.setForeground(new java.awt.Color(189, 195, 199));
        lblKey.setText("PASSWORD");
        pnlLogin.add(lblKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        txfUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pnlLogin.add(txfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 240, -1));

        btnLogin.setBackground(new java.awt.Color(10, 107, 207));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnLogin.setText("OK");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, -1, -1));

        lblLogin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(0, 153, 51));
        lblLogin.setText("LOGIN");
        pnlLogin.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        lblErrorKey.setForeground(new java.awt.Color(255, 158, 0));
        lblErrorKey.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlLogin.add(lblErrorKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 430, -1));

        psfKey.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pnlLogin.add(psfKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 240, -1));
        pnlLogin.add(lblIconKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));
        pnlLogin.add(lblIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 64)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 51));
        lblTitle.setText("ESPE SEAPORT");
        pnlLogin.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jPanel1.add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1296, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        new ViewMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblErrorKey;
    private javax.swing.JLabel lblIconKey;
    private javax.swing.JLabel lblIconUser;
    private javax.swing.JLabel lblKey;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField psfKey;
    private javax.swing.JTextField txfUser;
    // End of variables declaration//GEN-END:variables
}
