/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Manfred Armijos
 */
public class ViewStats extends javax.swing.JFrame {

    /**
     * Creates new form Plantilla
     */
    public ViewStats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbSubtotalT = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lblDiscountT = new javax.swing.JLabel();
        lblSubtotal2T = new javax.swing.JLabel();
        lblSubtotal2 = new javax.swing.JLabel();
        lbSubtotalT1 = new javax.swing.JLabel();
        lblDiscountT1 = new javax.swing.JLabel();
        lblSubtotal2T1 = new javax.swing.JLabel();
        lblSubtotal1 = new javax.swing.JLabel();
        lblDiscount1 = new javax.swing.JLabel();
        lblSubtotal3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbSubtotalT2 = new javax.swing.JLabel();
        lblSubtotal4 = new javax.swing.JLabel();
        lblDiscount2 = new javax.swing.JLabel();
        lblDiscountT2 = new javax.swing.JLabel();
        lblSubtotal2T2 = new javax.swing.JLabel();
        lblSubtotal5 = new javax.swing.JLabel();
        lbSubtotalT3 = new javax.swing.JLabel();
        lblDiscountT3 = new javax.swing.JLabel();
        lblSubtotal2T3 = new javax.swing.JLabel();
        lblSubtotal6 = new javax.swing.JLabel();
        lblDiscount3 = new javax.swing.JLabel();
        lblSubtotal7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbSubtotalT4 = new javax.swing.JLabel();
        lblSubtotal8 = new javax.swing.JLabel();
        lblDiscount4 = new javax.swing.JLabel();
        lblDiscountT4 = new javax.swing.JLabel();
        lblSubtotal2T4 = new javax.swing.JLabel();
        lblSubtotal9 = new javax.swing.JLabel();
        lbSubtotalT5 = new javax.swing.JLabel();
        lblDiscountT5 = new javax.swing.JLabel();
        lblSubtotal2T5 = new javax.swing.JLabel();
        lblSubtotal10 = new javax.swing.JLabel();
        lblDiscount5 = new javax.swing.JLabel();
        lblSubtotal11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(15, 20, 25));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(30, 40, 53));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(232, 238, 244));
        jLabel3.setText("PORT");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        lbSubtotalT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbSubtotalT.setForeground(new java.awt.Color(189, 195, 199));
        lbSubtotalT.setText("---");
        jPanel2.add(lbSubtotalT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblSubtotal.setBackground(new java.awt.Color(15, 26, 43));
        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal.setOpaque(true);
        jPanel2.add(lblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 110, 30));

        lblDiscount.setBackground(new java.awt.Color(15, 26, 43));
        lblDiscount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiscount.setForeground(new java.awt.Color(189, 195, 199));
        lblDiscount.setOpaque(true);
        jPanel2.add(lblDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 110, 30));

        lblDiscountT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiscountT.setForeground(new java.awt.Color(189, 195, 199));
        lblDiscountT.setText("---");
        jPanel2.add(lblDiscountT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblSubtotal2T.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal2T.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal2T.setText("---");
        jPanel2.add(lblSubtotal2T, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lblSubtotal2.setBackground(new java.awt.Color(15, 26, 43));
        lblSubtotal2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal2.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal2.setOpaque(true);
        jPanel2.add(lblSubtotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 110, 30));

        lbSubtotalT1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbSubtotalT1.setForeground(new java.awt.Color(189, 195, 199));
        lbSubtotalT1.setText("---");
        jPanel2.add(lbSubtotalT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lblDiscountT1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiscountT1.setForeground(new java.awt.Color(189, 195, 199));
        lblDiscountT1.setText("---");
        jPanel2.add(lblDiscountT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        lblSubtotal2T1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal2T1.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal2T1.setText("---");
        jPanel2.add(lblSubtotal2T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        lblSubtotal1.setBackground(new java.awt.Color(15, 26, 43));
        lblSubtotal1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal1.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal1.setOpaque(true);
        jPanel2.add(lblSubtotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 110, 30));

        lblDiscount1.setBackground(new java.awt.Color(15, 26, 43));
        lblDiscount1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiscount1.setForeground(new java.awt.Color(189, 195, 199));
        lblDiscount1.setOpaque(true);
        jPanel2.add(lblDiscount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 110, 30));

        lblSubtotal3.setBackground(new java.awt.Color(15, 26, 43));
        lblSubtotal3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal3.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal3.setOpaque(true);
        jPanel2.add(lblSubtotal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 110, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 390, 570));

        jButton1.setBackground(new java.awt.Color(10, 107, 207));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 20, 50, 70));

        jPanel3.setBackground(new java.awt.Color(30, 40, 53));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(232, 238, 244));
        jLabel4.setText("DOCK");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        lbSubtotalT2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbSubtotalT2.setForeground(new java.awt.Color(189, 195, 199));
        lbSubtotalT2.setText("---");
        jPanel3.add(lbSubtotalT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblSubtotal4.setBackground(new java.awt.Color(15, 26, 43));
        lblSubtotal4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal4.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal4.setOpaque(true);
        jPanel3.add(lblSubtotal4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 110, 30));

        lblDiscount2.setBackground(new java.awt.Color(15, 26, 43));
        lblDiscount2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiscount2.setForeground(new java.awt.Color(189, 195, 199));
        lblDiscount2.setOpaque(true);
        jPanel3.add(lblDiscount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 110, 30));

        lblDiscountT2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiscountT2.setForeground(new java.awt.Color(189, 195, 199));
        lblDiscountT2.setText("---");
        jPanel3.add(lblDiscountT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblSubtotal2T2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal2T2.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal2T2.setText("---");
        jPanel3.add(lblSubtotal2T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lblSubtotal5.setBackground(new java.awt.Color(15, 26, 43));
        lblSubtotal5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal5.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal5.setOpaque(true);
        jPanel3.add(lblSubtotal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 110, 30));

        lbSubtotalT3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbSubtotalT3.setForeground(new java.awt.Color(189, 195, 199));
        lbSubtotalT3.setText("---");
        jPanel3.add(lbSubtotalT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lblDiscountT3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiscountT3.setForeground(new java.awt.Color(189, 195, 199));
        lblDiscountT3.setText("---");
        jPanel3.add(lblDiscountT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        lblSubtotal2T3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal2T3.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal2T3.setText("---");
        jPanel3.add(lblSubtotal2T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        lblSubtotal6.setBackground(new java.awt.Color(15, 26, 43));
        lblSubtotal6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal6.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal6.setOpaque(true);
        jPanel3.add(lblSubtotal6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 110, 30));

        lblDiscount3.setBackground(new java.awt.Color(15, 26, 43));
        lblDiscount3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiscount3.setForeground(new java.awt.Color(189, 195, 199));
        lblDiscount3.setOpaque(true);
        jPanel3.add(lblDiscount3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 110, 30));

        lblSubtotal7.setBackground(new java.awt.Color(15, 26, 43));
        lblSubtotal7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal7.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal7.setOpaque(true);
        jPanel3.add(lblSubtotal7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 110, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 390, 570));

        jPanel4.setBackground(new java.awt.Color(30, 40, 53));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(232, 238, 244));
        jLabel5.setText("BILLS");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        lbSubtotalT4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbSubtotalT4.setForeground(new java.awt.Color(189, 195, 199));
        lbSubtotalT4.setText("---");
        jPanel4.add(lbSubtotalT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblSubtotal8.setBackground(new java.awt.Color(15, 26, 43));
        lblSubtotal8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal8.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal8.setOpaque(true);
        jPanel4.add(lblSubtotal8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 110, 30));

        lblDiscount4.setBackground(new java.awt.Color(15, 26, 43));
        lblDiscount4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiscount4.setForeground(new java.awt.Color(189, 195, 199));
        lblDiscount4.setOpaque(true);
        jPanel4.add(lblDiscount4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 110, 30));

        lblDiscountT4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiscountT4.setForeground(new java.awt.Color(189, 195, 199));
        lblDiscountT4.setText("---");
        jPanel4.add(lblDiscountT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblSubtotal2T4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal2T4.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal2T4.setText("---");
        jPanel4.add(lblSubtotal2T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lblSubtotal9.setBackground(new java.awt.Color(15, 26, 43));
        lblSubtotal9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal9.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal9.setOpaque(true);
        jPanel4.add(lblSubtotal9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 110, 30));

        lbSubtotalT5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbSubtotalT5.setForeground(new java.awt.Color(189, 195, 199));
        lbSubtotalT5.setText("---");
        jPanel4.add(lbSubtotalT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lblDiscountT5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiscountT5.setForeground(new java.awt.Color(189, 195, 199));
        lblDiscountT5.setText("---");
        jPanel4.add(lblDiscountT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        lblSubtotal2T5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal2T5.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal2T5.setText("---");
        jPanel4.add(lblSubtotal2T5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        lblSubtotal10.setBackground(new java.awt.Color(15, 26, 43));
        lblSubtotal10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal10.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal10.setOpaque(true);
        jPanel4.add(lblSubtotal10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 110, 30));

        lblDiscount5.setBackground(new java.awt.Color(15, 26, 43));
        lblDiscount5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiscount5.setForeground(new java.awt.Color(189, 195, 199));
        lblDiscount5.setOpaque(true);
        jPanel4.add(lblDiscount5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 110, 30));

        lblSubtotal11.setBackground(new java.awt.Color(15, 26, 43));
        lblSubtotal11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal11.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal11.setOpaque(true);
        jPanel4.add(lblSubtotal11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 110, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 390, 570));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 238, 244));
        jLabel1.setText("ESTADISTICAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 290, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1296, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ViewMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbSubtotalT;
    private javax.swing.JLabel lbSubtotalT1;
    private javax.swing.JLabel lbSubtotalT2;
    private javax.swing.JLabel lbSubtotalT3;
    private javax.swing.JLabel lbSubtotalT4;
    private javax.swing.JLabel lbSubtotalT5;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblDiscount1;
    private javax.swing.JLabel lblDiscount2;
    private javax.swing.JLabel lblDiscount3;
    private javax.swing.JLabel lblDiscount4;
    private javax.swing.JLabel lblDiscount5;
    private javax.swing.JLabel lblDiscountT;
    private javax.swing.JLabel lblDiscountT1;
    private javax.swing.JLabel lblDiscountT2;
    private javax.swing.JLabel lblDiscountT3;
    private javax.swing.JLabel lblDiscountT4;
    private javax.swing.JLabel lblDiscountT5;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotal1;
    private javax.swing.JLabel lblSubtotal10;
    private javax.swing.JLabel lblSubtotal11;
    private javax.swing.JLabel lblSubtotal2;
    private javax.swing.JLabel lblSubtotal2T;
    private javax.swing.JLabel lblSubtotal2T1;
    private javax.swing.JLabel lblSubtotal2T2;
    private javax.swing.JLabel lblSubtotal2T3;
    private javax.swing.JLabel lblSubtotal2T4;
    private javax.swing.JLabel lblSubtotal2T5;
    private javax.swing.JLabel lblSubtotal3;
    private javax.swing.JLabel lblSubtotal4;
    private javax.swing.JLabel lblSubtotal5;
    private javax.swing.JLabel lblSubtotal6;
    private javax.swing.JLabel lblSubtotal7;
    private javax.swing.JLabel lblSubtotal8;
    private javax.swing.JLabel lblSubtotal9;
    // End of variables declaration//GEN-END:variables
}
