/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Manfred Armijos
 */
public class ViewDock extends javax.swing.JFrame {

    /**
     * Creates new form Plantilla
     */
    public ViewDock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pnlDock = new javax.swing.JPanel();
        lblServName = new javax.swing.JLabel();
        lblServImo = new javax.swing.JLabel();
        lblServLength = new javax.swing.JLabel();
        lblServQuantity = new javax.swing.JLabel();
        btnDock = new javax.swing.JButton();
        lblServType = new javax.swing.JLabel();
        lblServCapacity = new javax.swing.JLabel();
        lblErrorDock = new javax.swing.JLabel();
        lblServImoT = new javax.swing.JLabel();
        lblServLengthT = new javax.swing.JLabel();
        lblServCapacityT = new javax.swing.JLabel();
        lblServQuantityT = new javax.swing.JLabel();
        pnlOperation = new javax.swing.JPanel();
        lblOperation = new javax.swing.JLabel();
        btnOperation = new javax.swing.JButton();
        rbtLoading = new javax.swing.JRadioButton();
        rbtUnloading = new javax.swing.JRadioButton();
        lblExtras = new javax.swing.JLabel();
        chbRefuel = new javax.swing.JCheckBox();
        chbMaintenance = new javax.swing.JCheckBox();
        chbClean = new javax.swing.JCheckBox();
        pnlPayment = new javax.swing.JPanel();
        lblIVAT = new javax.swing.JLabel();
        lblDiscountT = new javax.swing.JLabel();
        lblTotalT = new javax.swing.JLabel();
        btnBilling = new javax.swing.JButton();
        lblPayment = new javax.swing.JLabel();
        lbSubtotalT = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblSubtotal2T = new javax.swing.JLabel();
        lblSubtotal2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(15, 20, 25));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(30, 40, 53));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 110, 90, 120));

        jButton1.setBackground(new java.awt.Color(10, 107, 207));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 100, 70));

        pnlDock.setBackground(new java.awt.Color(30, 40, 53));
        pnlDock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblServName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServName.setForeground(new java.awt.Color(189, 195, 199));
        lblServName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServName.setText("--");
        pnlDock.add(lblServName, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 90, 270, -1));

        lblServImo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServImo.setForeground(new java.awt.Color(189, 195, 199));
        lblServImo.setText("--");
        pnlDock.add(lblServImo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        lblServLength.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServLength.setForeground(new java.awt.Color(189, 195, 199));
        lblServLength.setText("--");
        pnlDock.add(lblServLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        lblServQuantity.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServQuantity.setForeground(new java.awt.Color(189, 195, 199));
        lblServQuantity.setText("--");
        pnlDock.add(lblServQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        btnDock.setBackground(new java.awt.Color(10, 107, 207));
        btnDock.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDock.setText("Dock");
        btnDock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDockActionPerformed(evt);
            }
        });
        pnlDock.add(btnDock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 200, 50));

        lblServType.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblServType.setForeground(new java.awt.Color(189, 195, 199));
        lblServType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServType.setText("Type");
        pnlDock.add(lblServType, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, 280, -1));

        lblServCapacity.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServCapacity.setForeground(new java.awt.Color(189, 195, 199));
        lblServCapacity.setText("--");
        pnlDock.add(lblServCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        lblErrorDock.setForeground(new java.awt.Color(255, 158, 0));
        pnlDock.add(lblErrorDock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 200, -1));

        lblServImoT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServImoT.setForeground(new java.awt.Color(189, 195, 199));
        lblServImoT.setText("IMO");
        pnlDock.add(lblServImoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lblServLengthT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServLengthT.setForeground(new java.awt.Color(189, 195, 199));
        lblServLengthT.setText("Length");
        pnlDock.add(lblServLengthT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        lblServCapacityT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServCapacityT.setForeground(new java.awt.Color(189, 195, 199));
        lblServCapacityT.setText("Capacity");
        pnlDock.add(lblServCapacityT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        lblServQuantityT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServQuantityT.setForeground(new java.awt.Color(189, 195, 199));
        lblServQuantityT.setText("Quantity");
        pnlDock.add(lblServQuantityT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jPanel1.add(pnlDock, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 290, 560));

        pnlOperation.setBackground(new java.awt.Color(30, 40, 53));
        pnlOperation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOperation.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblOperation.setForeground(new java.awt.Color(189, 195, 199));
        lblOperation.setText("Operation");
        pnlOperation.add(lblOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        btnOperation.setBackground(new java.awt.Color(10, 107, 207));
        btnOperation.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnOperation.setText("Operate");
        btnOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperationActionPerformed(evt);
            }
        });
        pnlOperation.add(btnOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 200, 50));

        rbtLoading.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbtLoading.setForeground(new java.awt.Color(255, 255, 255));
        rbtLoading.setText("Loading");
        rbtLoading.setContentAreaFilled(false);
        pnlOperation.add(rbtLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        rbtUnloading.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbtUnloading.setForeground(new java.awt.Color(255, 255, 255));
        rbtUnloading.setText("Unloading");
        rbtUnloading.setContentAreaFilled(false);
        pnlOperation.add(rbtUnloading, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        lblExtras.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblExtras.setForeground(new java.awt.Color(255, 255, 255));
        lblExtras.setText("Extras");
        pnlOperation.add(lblExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        chbRefuel.setBackground(new java.awt.Color(102, 153, 255));
        chbRefuel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chbRefuel.setForeground(new java.awt.Color(255, 255, 255));
        chbRefuel.setText("Refuel");
        chbRefuel.setContentAreaFilled(false);
        chbRefuel.setFocusPainted(false);
        pnlOperation.add(chbRefuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        chbMaintenance.setBackground(new java.awt.Color(102, 153, 255));
        chbMaintenance.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chbMaintenance.setForeground(new java.awt.Color(255, 255, 255));
        chbMaintenance.setText("Maintenance");
        chbMaintenance.setContentAreaFilled(false);
        chbMaintenance.setFocusPainted(false);
        pnlOperation.add(chbMaintenance, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        chbClean.setBackground(new java.awt.Color(102, 153, 255));
        chbClean.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chbClean.setForeground(new java.awt.Color(255, 255, 255));
        chbClean.setText("Clean");
        chbClean.setContentAreaFilled(false);
        chbClean.setFocusPainted(false);
        pnlOperation.add(chbClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jPanel1.add(pnlOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 290, 560));

        pnlPayment.setBackground(new java.awt.Color(30, 40, 53));
        pnlPayment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIVAT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblIVAT.setForeground(new java.awt.Color(189, 195, 199));
        lblIVAT.setText("IVA");
        pnlPayment.add(lblIVAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lblDiscountT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiscountT.setForeground(new java.awt.Color(189, 195, 199));
        lblDiscountT.setText("Discount");
        pnlPayment.add(lblDiscountT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblTotalT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotalT.setForeground(new java.awt.Color(189, 195, 199));
        lblTotalT.setText("Total");
        pnlPayment.add(lblTotalT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        btnBilling.setBackground(new java.awt.Color(10, 107, 207));
        btnBilling.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBilling.setText("Bill");
        btnBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillingActionPerformed(evt);
            }
        });
        pnlPayment.add(btnBilling, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 200, 50));

        lblPayment.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPayment.setForeground(new java.awt.Color(189, 195, 199));
        lblPayment.setText("Payment");
        pnlPayment.add(lblPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lbSubtotalT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbSubtotalT.setForeground(new java.awt.Color(189, 195, 199));
        lbSubtotalT.setText("Subtotal");
        pnlPayment.add(lbSubtotalT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblTotal.setBackground(new java.awt.Color(15, 26, 43));
        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(189, 195, 199));
        lblTotal.setOpaque(true);
        pnlPayment.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 110, 30));

        lblSubtotal.setBackground(new java.awt.Color(15, 26, 43));
        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal.setOpaque(true);
        pnlPayment.add(lblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 110, 30));

        lblDiscount.setBackground(new java.awt.Color(15, 26, 43));
        lblDiscount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDiscount.setForeground(new java.awt.Color(189, 195, 199));
        lblDiscount.setOpaque(true);
        pnlPayment.add(lblDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 110, 30));

        lblIVA.setBackground(new java.awt.Color(15, 26, 43));
        lblIVA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblIVA.setForeground(new java.awt.Color(189, 195, 199));
        lblIVA.setOpaque(true);
        pnlPayment.add(lblIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 110, 30));

        lblSubtotal2T.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal2T.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal2T.setText("Subtotal");
        pnlPayment.add(lblSubtotal2T, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lblSubtotal2.setBackground(new java.awt.Color(15, 26, 43));
        lblSubtotal2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal2.setForeground(new java.awt.Color(189, 195, 199));
        lblSubtotal2.setOpaque(true);
        pnlPayment.add(lblSubtotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 110, 30));

        jPanel1.add(pnlPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 290, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1296, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDockActionPerformed
        //getPort().dockVessel();
    }//GEN-LAST:event_btnDockActionPerformed

    private void btnOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperationActionPerformed
        //getPort().operations();
    }//GEN-LAST:event_btnOperationActionPerformed

    private void btnBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingActionPerformed
        //getPort().bill();
    }//GEN-LAST:event_btnBillingActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ViewMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBilling;
    private javax.swing.JButton btnDock;
    private javax.swing.JButton btnOperation;
    private javax.swing.JCheckBox chbClean;
    private javax.swing.JCheckBox chbMaintenance;
    private javax.swing.JCheckBox chbRefuel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbSubtotalT;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblDiscountT;
    private javax.swing.JLabel lblErrorDock;
    private javax.swing.JLabel lblExtras;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblIVAT;
    private javax.swing.JLabel lblOperation;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblServCapacity;
    private javax.swing.JLabel lblServCapacityT;
    private javax.swing.JLabel lblServImo;
    private javax.swing.JLabel lblServImoT;
    private javax.swing.JLabel lblServLength;
    private javax.swing.JLabel lblServLengthT;
    private javax.swing.JLabel lblServName;
    private javax.swing.JLabel lblServQuantity;
    private javax.swing.JLabel lblServQuantityT;
    private javax.swing.JLabel lblServType;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotal2;
    private javax.swing.JLabel lblSubtotal2T;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalT;
    private javax.swing.JPanel pnlDock;
    private javax.swing.JPanel pnlOperation;
    private javax.swing.JPanel pnlPayment;
    private javax.swing.JRadioButton rbtLoading;
    private javax.swing.JRadioButton rbtUnloading;
    // End of variables declaration//GEN-END:variables
}
